from flask import Flask, request, jsonify
from flask_cors import CORS
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from waitress import serve

app = Flask(__name__)
CORS(app, resources={r"/send-email": {"origins": "*"}})

@app.route('/send-email', methods=['POST'])
def send_email():
    data = request.json
    contact = data.get('contact', {})
    country = data.get('countries', {}).get('base', 'N/A')
    expansion = ', '.join(data.get('countries', {}).get('expansion', [])) or 'None'
    services = ', '.join(data.get('services', [])) or 'None'
    addons = ', '.join(data.get('addons', [])) or 'None'
    total = data.get('finalTotal', 0)
    timeline = data.get('timeline', 'N/A')
    stage = data.get('businessStage', 'N/A')
    plan = data.get('plan', 'eBranch')
    name = contact.get('name', 'Client')
    email = contact.get('email', 'N/A')
    phone = contact.get('phone', 'N/A')

    # ✅ Updated HTML with message inside the table
    html = f"""
    <html>
      <body style="font-family: Arial, sans-serif; background-color: #f9f9f9; padding: 20px;">
        <div style="max-width: 600px; margin: auto; background-color: #fff; padding: 30px; border: 1px solid #ddd; border-radius: 10px;">

          <h2 style="color: #007BFF;">📋 Your Business Setup Plan Summary</h2>

          <p style="margin-bottom: 30px;">
            Dear {name},<br><br>
            Thank you for reaching out to <strong>YourCompanyName</strong>. We’ve received your inquiry and our team will review your information shortly.<br>
            Here's a summary of the information you provided:
          </p>

          <table style="width: 100%; border-collapse: separate; border-spacing: 10px;">
            <tr><td><strong>👤 Name:</strong></td><td>{name}</td></tr>
            <tr><td><strong>📧 Email:</strong></td><td>{email}</td></tr>
            <tr><td><strong>📞 Phone:</strong></td><td>{phone}</td></tr>
            <tr><td><strong>💼 Business Stage:</strong></td><td>{stage}</td></tr>
            <tr><td><strong>🌍 Country:</strong></td><td>{country}</td></tr>
            <tr><td><strong>🌐 Expansion Regions:</strong></td><td>{expansion}</td></tr>
            <tr><td><strong>⏱ Timeline:</strong></td><td>{timeline}</td></tr>
            <tr><td><strong>🛠 Services:</strong></td><td>{services}</td></tr>
            <tr><td><strong>➕ Add-ons:</strong></td><td>{addons}</td></tr>
            <tr><td><strong>🏷 Recommended Plan:</strong></td><td>{plan}</td></tr>
            <tr><td style="color: #28a745;"><strong>💶 Total Estimated Cost:</strong></td><td style="color: #28a745;"><strong>€{total}</strong></td></tr>
            <tr>
              <td colspan="2" style="padding-top: 20px; border-top: 1px solid #ddd; font-style: italic;">
                ☎️ Our team will reach out to you soon to take this forward. You can also reply to this email directly.
              </td>
            </tr>
          </table>

          <p style="font-size: 12px; color: #888; border-top: 1px solid #ddd; margin-top: 30px; padding-top: 10px;">
            This message was generated by YourCompanyName.com. If you didn’t request this, please ignore.
          </p>

        </div>
      </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg['Subject'] = "📋 Your Business Setup Plan Summary"
    msg['From'] = 'pardhasaradhi52609@gmail.com'
    msg['To'] = email
    msg.attach(MIMEText(html, "html"))

    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.login('pardhasaradhi52609@gmail.com', 'bkla cbbn svoe nfyj')  # Use app password
        server.send_message(msg)
        server.quit()
        return jsonify({'status': 'success'})
    except Exception as e:
        return jsonify({'status': 'error', 'error': str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    serve(app, host='0.0.0.0', port=port)

